routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::prefix('admin-panel')->middleware('auth:admin')->group(function () {

    Route::get('/', 'AdminController@index')->name('admin-panel');
    Route::get('/logout', 'Auth\AuthController@logout')->name('admin.logout');
    Route::get('categories/data', 'CategoryController@data')->name('categories.data');
    Route::get('categories/getParent', 'CategoryController@getParent')->name('categories.getParent');
    Route::get('categories/getFChildrenById', 'CategoryController@getFChildrenById')->name('categories.getFChildrenById');
    Route::get('categories/getTChildrenById', 'CategoryController@getTChildrenById')->name('categories.getTChildrenById');
    Route::get('categories/getRChildrenById', 'CategoryController@getRChildrenById')->name('categories.getRChildrenById');
    Route::get('categories/getChildren', 'CategoryController@getChildren')->name('categories.getChildren');
    Route::resource('categories', 'CategoryController');
    Route::get('products/data', 'ProductController@data')->name('products.data');
    Route::resource('products', 'ProductController');
});
Route::prefix('admin-panel')->middleware('guest:admin')->group(function () {

    Route::get('/login', 'Auth\AuthController@login')->name('admin.login');
    Route::post('/login', 'Auth\AuthController@doLogin')->name('admin.doLogin');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
\Illuminate\Support\Facades\Auth::routes();

Route::get('orders/category/{id}', 'OrderController@getSubCategory')->name('orders.category');
Route::get('orders/categories/', 'OrderController@categories')->name('orders.categories');
Route::get('category/products/{id}', 'OrderController@categoryProducts')->name('category.products');
Route::get('storeOrders/{id}', 'OrderController@storeOrder')->name('storeOrder');
Route::get('updateQuantity', 'OrderController@updateQuantity')->name('product.updateQuantity');
Route::get('deleteOrder', 'OrderController@deleteOrder')->name('deleteOrder');
Route::resource('orders', 'OrderController');

Route::get('/products', function () {

    return view('front.orders.products');
});

resources/views/admins/index.blade.php
@extends('admins.layouts.master')


@section('content_header')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">الرئيسيه</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
@endsection
@section('content')

    <section class="content">
        <div class="row">
            <div class="col-md-6 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>{{$products->count()}}</h3>

                        <p>New Product</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a href="{{route('products.index')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>


            <div class="col-md-6 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>{{$categories->count()}}</h3>

                        <p>New Category</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <a href="{{route('categories.index')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>

    </section>
    <!-- /.content -->

@endsection